version: "3.1"

services:
  frontend:
    build:
      context: frontend
    command: bash -c "yarn install && yarn start"
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      CI: "true"
    links:
      - backend:backend
    networks:
      - frontend
      - backend

  backend:
    build:
      context: backend
    command: bash --login -c "yarn install && yarn develop"
    ports:
      - 1337:1337
    working_dir: /app
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    links:
      - db:db
    networks:
      - backend

  db:
    image: postgres:12.3
    volumes:
      - .data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  frontend_node_modules:
  backend_node_modules:
